//v6
var Games = [{
  "Title":"Mine-Blocks",
  "Link":"https://jayvir101.github.io/lightning-resources/Games/Mine-Blocks.swf",
  "Icon":"https://jayvir101.github.io/lightning-resources/Games/Icons/Mine-Blocks.png",
  "Iframe":true
},{
  "Title":"Flood-Runner",
  "Link":"https://jayvir101.github.io/lightning-resources/Games/Flood-Runner.swf",
  "Icon":"https://jayvir101.github.io/lightning-resources/Games/Icons/Flood-Runner.png",
  "Iframe":true
},{
  "Title":"Fancy-Pants",
  "Link":"https://jayvir101.github.io/lightning-resources/Games/Fancy-Pants.swf",
  "Icon":"https://jayvir101.github.io/lightning-resources/Games/Icons/Fancy-Pants.png",
  "Iframe":true
},{
  "Title":"Dune-Buggy",
  "Link":"https://jayvir101.github.io/lightning-resources/Games/Dune-Buggy.swf",
  "Icon":"https://jayvir101.github.io/lightning-resources/Games/Icons/Dune-Buggy.png",
  "Iframe":true
},{
  "Title":"Crush-The-Castle",
  "Link":"https://jayvir101.github.io/lightning-resources/Games/Crush-The-Castle.swf",
  "Icon":"https://jayvir101.github.io/lightning-resources/Games/Icons/Crush-The-Castle.png",
  "Iframe":true
},{
  "Title":"Car-Eats-Car",
  "Link":"https://jayvir101.github.io/lightning-resources/Games/Car-Eats-Car.swf",
  "Icon":"https://jayvir101.github.io/lightning-resources/Games/Icons/Car-Eats-Car.png",
  "Iframe":true
},{
  "Title":"Bad-Piggies",
  "Link":"https://jayvir101.github.io/lightning-resources/Games/Bad-Piggies.swf",
  "Icon":"https://jayvir101.github.io/lightning-resources/Games/Icons/Bad-Piggies.png",
  "Iframe":true
},{
  "Title":"Rocketeer",
  "Link":"https://jayvir101.github.io/lightning-resources/Games/Rocketeer.swf",
  "Icon":"https://jayvir101.github.io/lightning-resources/Games/Icons/Rocketeer.png",
  "Iframe":true
},{
  "Title":"Snail-Bob",
  "Link":"https://jayvir101.github.io/lightning-resources/Games/Snail-Bob.swf",
  "Icon":"https://jayvir101.github.io/lightning-resources/Games/Icons/Snail-Bob.png",
  "Iframe":true
},{
  "Title":"agario",
  "Link":"http://www.agar.io",
  "Icon":"https://jayvir101.github.io/lightning-resources/Games/Icons/agario.png",
  "Iframe":false,
  "Online":true
},{
  "Title":"ZombsRoyaleio",
  "Link":"http://www.ZombsRoyale.io",
  "Icon":"https://jayvir101.github.io/lightning-resources/Games/Icons/ZombsRoyaleio.png",
  "Iframe":false,
  "Online":true
},{
  "Title":"survivio",
  "Link":"http://surviv.io",
  "Icon":"https://jayvir101.github.io/lightning-resources/Games/Icons/survivio.png",
  "Iframe":false,
  "Online":true
},{
  "Title":"wingsio",
  "Link":"http://www.wings.io",
  "Icon":"https://jayvir101.github.io/lightning-resources/Games/Icons/wingsio.png",
  "Iframe":false,
  "Online":true
},{
  "Title":"Sonic",
  "Link":"https://jayvir101.github.io/lightning-resources/Games/Sonic.swf",
  "Icon":"https://jayvir101.github.io/lightning-resources/Games/Icons/Sonic.png",
  "Iframe":true
},{
  "Title":"Racing-Game",
  "Link":"https://jayvir101.github.io/lightning-resources/Games/Racing-Game.swf",
  "Icon":"https://jayvir101.github.io/lightning-resources/Games/Icons/Racing-Game.png",
  "Iframe":true

},{
  "Title":"Pacxon",
  "Link":"https://jayvir101.github.io/lightning-resources/Games/Pacxon.swf",
  "Icon":"https://jayvir101.github.io/lightning-resources/Games/Icons/Pacxon.png",
  "Iframe":true

},{
  "Title":"Chat",
  "Link":"https://jayvir101.github.io/lightning/Chat/",
  "Icon":"https://jayvir101.github.io/lightning/Chat/icon.png",
  "Iframe":false,
  "Online":true
},{
  "Title":"splixio",
  "Link":"http://splix.io",
  "Icon":"https://jayvir101.github.io/lightning-resources/Games/Icons/splixio.png",
  "Iframe":false,
  "Online":true
},{
  "Title":"slitherio",
  "Link":"http://slither.io",
  "Icon":"https://jayvir101.github.io/lightning-resources/Games/Icons/slitherio.png",
  "Iframe":false,
  "Online":true
},{
  "Title":"Goodgame-Empire",
  "Link":"https://media.goodgamestudios.com/games/empire/",
  "Icon":"https://jayvir101.github.io/lightning-resources/Games/Icons/Goodgame-Empire.png",
  "Iframe":false,
  "Online":true
},{
  "Title":"Tu-95",
  "Link":"https://jayvir101.github.io/lightning-resources/Games/Tu-95.swf",
  "Icon":"https://jayvir101.github.io/lightning-resources/Games/Icons/Tu-95.png",
  "Iframe":true

},{
  "Title":"Snake-Game",
  "Link":"https://jayvir101.github.io/lightning-resources/Games/Snake-Game.swf",
  "Icon":"https://jayvir101.github.io/lightning-resources/Games/Icons/Snake-Game.png",
  "Iframe":true

},{
  "Title":"RedBall",
  "Link":"https://jayvir101.github.io/lightning-resources/Games/RedBall.swf",
  "Icon":"https://jayvir101.github.io/lightning-resources/Games/Icons/RedBall.png",
  "Iframe":true

},{
  "Title":"2048",
  "Link":"https://gabrielecirulli.github.io/2048/",
  "Icon":"https://jayvir101.github.io/lightning-resources/Games/Icons/2048.png",
  "Iframe":false,
  "Online":true
},{
  "Title":"3d-Missile",
  "Link":"https://jayvir101.github.io/lightning-resources/Games/3d-Missile.swf",
  "Icon":"https://jayvir101.github.io/lightning-resources/Games/Icons/3d-Missile.png",
  "Iframe":true

},{
  "Title":"Bloxorz",
  "Link":"https://jayvir101.github.io/lightning-resources/Games/Bloxorz.swf",
  "Icon":"https://jayvir101.github.io/lightning-resources/Games/Icons/Bloxorz.png",
  "Iframe":true

},{
  "Title":"Settings",
  "Link":"https://jayvir101.github.io/lightning/Settings/",
  "Icon":"https://jayvir101.github.io/lightning-resources/Games/Icons/Settings.png",
  "Iframe":false
},{
  "Title":"Admin-Console",
  "Link":"https://jayvir101.github.io/lightning/Client2/login.html",
  "Icon":"https://jayvir101.github.io/lightning-resources/Games/Icons/Admin-Console.png",
  "Iframe":false,
  "Online":true
},{
  "Title":"brutalio",
  "Link":"http://brutal.io",
  "Icon":"https://jayvir101.github.io/lightning-resources/Games/Icons/brutalio.png",
  "Iframe":false,
  "Online":true
},{
  "Title":"Fishy",
  "Link":"https://jayvir101.github.io/lightning-resources/Games/Fishy.swf",
  "Icon":"https://jayvir101.github.io/lightning-resources/Games/Icons/Fishy.png",
  "Iframe":true

},{
  "Title":"Little-Alchemy",
  "Link":"https://littlealchemy.com/",
  "Icon":"https://jayvir101.github.io/lightning-resources/Games/Icons/Little-Alchemy.png",
  "Iframe":false,
  "Online":true
},{
  "Title":"QWOP",
  "Link":"https://jayvir101.github.io/lightning-resources/Games/QWOP.swf",
  "Icon":"https://jayvir101.github.io/lightning-resources/Games/Icons/QWOP.png",
  "Iframe":true

},{
  "Title":"Worlds-Hardest-Game-3",
  "Link":"https://jayvir101.github.io/lightning-resources/Games/Worlds-Hardest-Game-3.swf",
  "Icon":"https://jayvir101.github.io/lightning-resources/Games/Icons/Worlds-Hardest-Game-3.png",
  "Iframe":true

},{
  "Title":"superhexio",
  "Link":"http://superhex.io/",
  "Icon":"https://jayvir101.github.io/lightning-resources/Games/Icons/superhexio.png",
  "Iframe":false,
  "Online":true
},{
  "Title":"Tetris",
  "Link":"https://jayvir101.github.io/lightning-resources/Games/Tetris.swf",
  "Icon":"https://jayvir101.github.io/lightning-resources/Games/Icons/Tetris.png",
  "Iframe":true

},{
  "Title":"Pacman",
  "Link":"https://jayvir101.github.io/lightning-resources/Games/Pacman.swf",
  "Icon":"https://jayvir101.github.io/lightning-resources/Games/Icons/Pacman.png",
  "Iframe":true

},{
  "Title":"Flappy-Bird",
  "Link":"https://jayvir101.github.io/lightning-resources/Games/Flappy-Bird.swf",
  "Icon":"https://jayvir101.github.io/lightning-resources/Games/Icons/Flappy-Bird.png",
  "Iframe":true

},{
  "Title":"Happy-Wheels",
  "Link":"https://jayvir101.github.io/lightning-resources/Games/Happy-Wheels.swf",
  "Icon":"https://jayvir101.github.io/lightning-resources/Games/Icons/Happy-Wheels.png",
  "Iframe":true

},{
  "Title":"40xEscape",
  "Link":"https://jayvir101.github.io/lightning-resources/Games/40xEscape.swf",
  "Icon":"https://jayvir101.github.io/lightning-resources/Games/Icons/40xEscape.png",
  "Iframe":true

},{
  "Title":"Sinuous",
  "Link":"http://www.sinuousgame.com/",
  "Icon":"https://jayvir101.github.io/lightning-resources/Games/Icons/Sinuous.png",
  "Iframe":false,
  "Online":true
},{
  "Title":"Tank-Trouble",
  "Link":"https://www.tanktrouble.com/includes/TankTrouble_v4.0.swf",
  "Icon":"https://jayvir101.github.io/lightning-resources/Games/Icons/Tank-Trouble.png",
  "Base":"https://www.tanktrouble.com/",
  "Iframe":true,
  "Online":true
}];